spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    baseline-on-migrate: true
    enabled: false
    active: true
    baseline-version: 0.0
    locations: classpath:db/migration/
  application:
    name: social-network-app
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=social_network_app;
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
  mail:
    host: smtp.mailtrap.io
#    port: 2525
    port: 587
    username: 60a00176f41dd9
    password: d95809f74f3897
#    password: ff67aef89c5bb6z
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

jwt:
  expiration:
    time: 90000
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

com.example.socialnetworkapp:
  time-zone-id: "Asia/Ho_Chi_Minh"
#  time-zone-id: "Europe/Berlin"
#  time-zone-id: "Singapore"
#  time-zone-id: "America/New_York"


server:
  port: 8080
  error:
    include-stacktrace: never

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.socialnetworkapp: DEBUG
#  file:
#    name: D:\Workplace\logs\social-network-app.log

