spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    baseline-on-migrate: true
    enabled: false
    active: true
    baseline-version: 0.0
    locations: classpath:db/migration/
#    driver-vendor: mysql
    driver-vendor: sqlserver
  application:
    name: social-network-app
  datasource:
#    url: jdbc:mysql://localhost:3306/social_network_app?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password: 123456789
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:sqlserver://localhost:1433;databaseName=social_network_app;
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQLDialect
      dialect: org.hibernate.dialect.SQLServer2012Dialect
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: d7537128965217
    password: ff67aef89c5bb6
#    password: ff67aef89c5bb6z
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

jwt:
  expiration:
    time: 90000
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key


server:
  port: 8080
  error:
    include-stacktrace: never

#logging:
#  file:
#    name: D:\Workplace\logs\social-network-app.log



