spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0.0
    locations: classpath:db/migration
  application:
    name: social-network-app
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_app?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: d7537128965217
    password: ff67aef89c5bb6
#    password: ff67aef89c5bb6z
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

server:
  port: 8080
  error:
    include-stacktrace: never

#logging:
#  file:
#    name: D:\Workplace\logs\social-network-app.log



